### PR TITLE
Feature Addition: Peek Window Scroll

### PR DESCRIPTION
**Pull request by ItsMeAshiq**
### Improvement
Made some improvements in the VI resize operation.
<hr>

### New Feature
Implemented Scroll Feature into the **Peek window**.

Now, users can scroll the Peek Window as similar to scrolling normal VIs.

VI Peek Window Scroll
<hr>

### Possible Scroll Operations
**Normal Scroll** → Scrolls Vertically
**Shift + Scroll** → Scrolls Vertically with extra distance
**Alt + Scroll** → Scrolls Horizontally
**Shift + Alt + Scroll** → Scrolls Horizontally with extra distance
<hr>

### CODE REVIEW

**Comment by jacobson3** [comment]
Cool addition, I'll have to mess with this more later but from a quick look I'm wondering if the BD vs FP check is really necessary.

**Comment by jacobson3** [comment]
@ItsMeAshiq Also, is there a reason why you removed the "Panel_PeekSubpanel: Mouse Down?" event? There doesn't seem to be any bad interactions between that event and the scroll event that you added.

**Comment by ItsMeAshiq** [comment]
> Cool addition, I'll have to mess with this more later but from a quick look I'm wondering if the BD vs FP check is really necessary.

Thought to also include **Front Panel** into the **Peek Window** for Future version, so  with a **Ctrl + E** shortcut, Front Panel can also be peeked.

This FP addition to the **Peek Window** would be very useful if the user wants to peek the FP during their drill down. 

And if a front panel is inserted into a sub panel, it implicitly has the scroll features except the **Alt + Scroll** → Horizontal Scroll.

I think that alone can be added to the FP Scroll once FP peeking is added.

**Comment by ItsMeAshiq** [comment]
> @ItsMeAshiq Also, is there a reason why you removed the "Panel_PeekSubpanel: Mouse Down?" event? There doesn't seem to be any bad interactions between that event and the scroll event that you added.

Yeah, it was messing with the Block Diagram, while panning its contents using **Ctrl + Shift + Mouse Down + Mouse Drag**.

Such as, when panning is started with the inserted Block Diagram, parallely mouse down event is processed on the Peek VI. Then even after releasing the mouse, the Block Diagram still being in the panning mode and pans the diagram at unexpected positions.

It stops only after after a Mouse Down on the block diagram.

**Comment by ItsMeAshiq** [comment]
And I have discovered a bug with this scroll, while scrolling over the **Scroll Bars**, it still implements the below mentioned interactions, 

> ### Possible Scroll Operations
> **Normal Scroll** → Scrolls Vertically
**Shift + Scroll** → Scrolls Vertically with extra distance
**Alt + Scroll** → Scrolls Horizontally
**Shift + Alt + Scroll** → Scrolls Horizontally with extra distance

It can be updated. Let me have some time to commit changes for this addition.

**Comment by ItsMeAshiq** [comment]
> And I have discovered a bug with this scroll, while scrolling over the **Scroll Bars**, it still implements the below mentioned interactions,
> 
> > ### Possible Scroll Operations
> > **Normal Scroll** → Scrolls Vertically
> > **Shift + Scroll** → Scrolls Vertically with extra distance
> > **Alt + Scroll** → Scrolls Horizontally
> > **Shift + Alt + Scroll** → Scrolls Horizontally with extra distance
> 
> It can be updated. Let me have some time to commit changes for this addition.

This bug is fixed with [this commit](https://github.com/jacobson3/VI-Peek/pull/32/commits/0e6116ce028fe76416019b08c71e8fe998ab99c9)

**Pull request merged**
